# scp upload
.PHONY: scp
scp:
	scp ./requirements.txt ./main.py ./Makefile pi@192.168.0.100:/home/pi/mimamori/mimamori-capture-screen

# pip install
.PHONY: pip-install
pip-install:
	pip install -r requirements.txt